[92] progress without error
steamclock/netable pull request #117
Opened 2023-01-23 17:23 UTC by amyoulton

Give the nature of this, I have decided to open a draft PR so the conversation within issue #92 can include the current code changes/examples.

2023-02-06 22:02 UTC, brendanlensink requested changes
A couple suggestions/comments to think about

Also we should probably bump the library version since we're adding new functionality ✨

2023-02-07 20:14 UTC, brendanlensink commented on Netable/Netable/Request.swift
> +    func postProcess(result: FinalResource) async throws -> FinalResource
@nbrooke it looks like you suggested the return value in the initial suggestion, is there a reason you thought we should keep it around?

2023-02-07 20:35 UTC, nbrooke commented on Netable/Netable/Request.swift
> +    func postProcess(result: FinalResource) async throws -> FinalResource
Having mutable structs (or actors) be Sendable is totally fine (as long as all the members are Sendable). It's only classes where you might need to make things immutable to get sendability. So the postProcess hook CAN modify some types, and it seems valuable to allow it as an option.

2023-02-07 20:41 UTC, brendanlensink commented on Netable/Netable/Request.swift
> +    func postProcess(result: FinalResource) async throws -> FinalResource
Fair enough, sorry for the confusion @amyoulton. Lets back out of that change 😬

2023-02-09 16:18 UTC, brendanlensink approved these changes
Looks good, before merging don't forget to add a blurb to the README explaining intended use 🚀

2023-02-13 22:20 UTC, merged

2023-02-13 22:20 UTC, amyoulton commented
@brendanlensink this is merged! You said you were going to do the tag and release stuff so just nudging about that! 👀